
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-26T11:39:43-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "34e1e405a7eed35a396ef8a29f42fc1a9c5ecdcf",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
